---
- name: Recreate personal enviroment
  hosts: localhost
  remote_user: manolo 

  pretasks:

    - name: Docker gpg key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable 

    - name: Spotify gpg key
      ansible.builtin.apt_key:
        url: https://download.spotify.com/debian/pubkey_0D811D58.gpg

    - name: Spotify repository        
      ansible.builtin.apt_repository:
        repo: deb http://repository.spotify.com stable non-free
    
    - name: VS Code gpg key
      ansible.builtin.apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc

    - name: VS Code repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main

    - name: Sublime Text 3 gpg key
      ansible.builtin.apt_key:
        url:  https://download.sublimetext.com/sublimehq-pub.gpg

    - name: Sublime Text 3 repository
      ansible.builtin.apt_repository:
        url: deb https://download.sublimetext.com/ apt/stable/

    - name: Install necessary things
      apt:
        name:
          - snapd
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
        update_cache: yes

    - name: Ensure projects directory
      ansible.builtin.file:
        src: /home/manolo/projets
        state: directory
      become_user: manolo

  tasks:
    
    - name: Install things
      block:

      - name: Installing tools
        apt:
          name:
            - git
            - vim
            - curl
            - wget
            - tar
            - zip
          state: present
          update_cache: yes
      
      - name: Installing whole programs
        apt:
          - firefox
          - code
          - spotify-client
          - sublime-text
        state: present
        update_cache: yes

      - name: Install whole programs with snap
        commmunity.general.snapd:
          - discord

      - name: Installing dev tools
        apt:
          name:
            - python3
            - python3-pip
            - build-essential
            - cmake
            - openjdk-11-jdk
            - openjdk-8-jdk
          state: present
          update_cache: yes

      - name: Install Rust
        ansible.builtin.shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Install Go
        ansible.builtin.unarchive:
          src: https://golang.org/dl/go1.15.6.linux-amd64.tar.gz
          usr: /usr/local/go/bin/
          remote_src: yes
      
      become: yes
      become_user: manolo

    - name: Download and setup dotfiles
      block:

      - name: .zshrc install
        copy:
          src: https://raw.githubusercontent.com/manoloesparta/stuff/master/dotfiles/zshrc
          dest: /home/manolo/.zshrc
          remote_src: yes
      
      - name: tmux.conf
        copy:
          src: https://raw.githubusercontent.com/manoloesparta/stuff/master/dotfiles/tmux.conf
          dest: /home/manolo/tmux.conf
          remote_src: yes
      
      - name: vimrc
        copy:
          src: https://raw.githubusercontent.com/manoloesparta/stuff/master/dotfiles/vimrc
          dest: /home/manolo/.vimrc
          remote_src: yes
      
      - name: gitconfig
        copy:
          src: https://raw.githubusercontent.com/manoloesparta/stuff/master/dotfiles/gitconfig
          dest: /home/manolo/.gitconfig
          remote_src: yes
      
      become: yes
      become_user: manolo
