---
- name: Recreate personal enviroment
  hosts: localhost
  remote_user: manolo 

  pretasks:

    - name: Adding certificates
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Adding repositories
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable 

    - name: Install necessary things
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
        update_cache: yes

  tasks:
    
    - name: Install things
      block:

      - name: Installing tools
        apt:
          name:
            - git
            - vim
            - curl
            - wget
            - tar
            - zip
          state: present
          update_cache: yes
      
      - name: Installing whole programs
        apt:
          - firefox
        state: present
        update_cache: yes

      - name: Installing dev tools
        apt:
          name:
            - python3
            - python3-pip
            - build-essential
          state: present
          update_cache: yes

      - name: Install Rust
        ansible.builtin.shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      # - name: Install Go
      
      become: yes
      become_user: manolo

    # - name: Download and setup dotfiles